import Head from "next/head";
import Image from "next/image";
import { Fragment } from "react";
import Box from "@mui/material/Box"
import Carousel from "../components/carousel/carousel";
import Layout from "../components/layout/Layout";
import Trending from "../components/trending/Trending"
import Container from "@mui/material/Container";
import FeaturedItem from "../components/Features/FeaturedItem";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main>
        <Container>
          <Carousel />
          <Trending />
          <Box sx={{p:1, mt:1}}>
            <FeaturedItem />
          </Box>
        </Container>
        </main>
      </Layout>
    </Fragment>
  );
}
