import Head from "next/head";
import { Fragment } from "react";
import Homepage from "../components/home/Homepage"

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>EasyShopping - shopping got so easy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage />     
    </Fragment>
  );
}
